export * from './components/Accordion'
export * from './components/AlertDialog'
export * from './components/Avatar'
export * from './components/Breadcrumb'
export * from './components/Button'
export * from './components/Calendar'
export * from './components/Card'
export * from './components/Checkbox'
export * from './components/Collapsible'
export * from './components/Combobox'
export * from './components/ContextMenu'
export * from './components/DatePicker'
export * from './components/Dialog'
export * from './components/Form'
export * from './components/icons'
export * from './components/Input'
export * from './components/Kpi'
export * from './components/Logo'
export * from './components/Menu'
export * from './components/Message'
export * from './components/Navigation'
export * from './components/NumberField'
export * from './components/Pagination'
export * from './components/Pill'
export * from './components/Popover'
export * from './components/ProgressBar'
export * from './components/Radio'
export * from './components/ScrollArea'
export * from './components/Select'
export * from './components/Separator'
export * from './components/SideNavigation'
export * from './components/Sidesheet'
export * from './components/Skeleton'
export * from './components/Slider'
export * from './components/Switch'
// Table is intentionally NOT re-exported from the barrel: it is the only component that pulls in
// @tanstack/react-table (an optional peer). Deep-import it instead — `@ogcr/design-system/Table` —
// so barrel consumers who never render a Table don't drag the peer into their graph.
export * from './components/Tabs'
export * from './components/Textarea'
export * from './components/Toast'
export * from './components/Toggle'
export * from './components/Toolbar'
export * from './components/Tooltip'

// Utilities (not components). cn() is the class-merge helper every component uses internally;
// exported so consumers can compose className overrides with the same clsx + tailwind-merge
// semantics. Also available as the dependency-free deep import `@ogcr/design-system/cn`.
export { cn } from './lib/cn'
